version: "3.8"
services:
  service3:
    # build: .
    image: safii/docker-vpn:${IMAGE_TAG}
    container_name: docker-vpn
    ports:
      - "3003:3003"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: always